FROM node:20-alpine
WORKDIR /app

# Copy lock files and package.json to leverage cache
COPY server/package*.json ./server/
COPY web/package*.json ./web/

RUN cd server && npm install
RUN cd web && npm install

# Copy source
COPY . .

# Build frontend first
RUN cd web && rm -rf dist && npm run build

# Build backend
RUN cd server && rm -rf dist && npm run build

EXPOSE 4000
WORKDIR /app/server
CMD ["node", "dist/index.js"]
